Add Loki and upgrade dashboards
aws-controllers-k8s/test-infra pull request #186
Opened 2022-03-03 23:32 UTC by RedbackThomson

Description of changes:
Switch from the `kube-prom` chart in the prometheus community repository, to the [`loki-stack`](https://github.com/grafana/helm-charts/tree/main/charts/loki-stack) which installs Loki, Grafana, Prometheus and Promtail. This new chart also upgrades the version of Grafana, requiring each of the dashboard panels to be updated.

Add a new panel to the `ACK Dashboard` called "Controller ERROR Logs" which reports any ACK controller logs containing the term `ERROR`. Unfortunately this version of Grafana does not come with K8s default dashboards.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-04 00:07 UTC, vijtrip2 commented
Is it possible to export and add another dashboard to monitor pod level Memory, CPU, Network and Disk IO. I found those metrics very important for soak test to validate that there is no memory leak and we used to get them from the K8s dashboards which got removed.

2022-03-04 22:03 UTC, vijtrip2 approved these changes

2022-03-05 22:05 UTC, jaypipes requested changes
@RedbackThomson this PR looks good, only I think you need to update the PR summary to accurately reflect what is in the PR now :)

2022-03-05 23:23 UTC, RedbackThomson commented
> @RedbackThomson this PR looks good, only I think you need to update the PR summary to accurately reflect what is in the PR now :)

Good call. Updated!

2022-03-05 23:34 UTC, jaypipes approved these changes
Thank you sir! :)

2022-03-05 23:34 UTC, jaypipes commented
/lgtm

2022-03-05 23:35 UTC, merged